version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Berlin"
    assignees:
      - "svenjacobs"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "androidx.compose.compiler*"
        exclude-patterns:
          - "org.jetbrains.kotlinx*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Berlin"
    assignees:
      - "svenjacobs"
