[versions]
android-gradle-plugin = "8.8.1"
androidx-activity = "1.10.0"
androidx-compose-bom = "2025.02.00" # https://developer.android.com/jetpack/compose/bom/bom-mapping
jetbrains-compose = "1.7.3"
kotlin = "2.1.10"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
slack-compose-lint-checks = "com.slack.lint.compose:compose-lint-checks:1.4.2"

# Test dependencies
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.6.1"
androidx-test-ext-junit = "androidx.test.ext:junit:1.2.1"
junit = "junit:junit:4.13.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ben-manes-versions = "com.github.ben-manes.versions:0.52.0"
nexus-publish = "io.github.gradle-nexus.publish-plugin:2.0.0"
kotlinter = "org.jmailen.kotlinter:5.0.1"
binary-compat-validator = "org.jetbrains.kotlinx.binary-compatibility-validator:0.17.0"
