[versions]
android-gradle-plugin = "9.0.1"
androidx-compose-bom = "2025.12.00"
jetbrains-compose = "1.10.1"
kotlin = "2.2.21"
reveal = "4.0.0"

[libraries]
androidx-core-ktx = "androidx.core:core-ktx:1.17.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.12.1"
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
reveal-core = { module = "com.svenjacobs.reveal:reveal-core", version.ref = "reveal" }
reveal-shapes = { module = "com.svenjacobs.reveal:reveal-shapes", version.ref = "reveal" }
compose-multiplatform-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrains-compose" }
compose-multiplatform-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrains-compose" }
compose-multiplatform-material3 = "org.jetbrains.compose.material3:material3:1.9.0"
compose-multiplatform-material-icons-extended = "org.jetbrains.compose.material:material-icons-extended:1.7.3"
compose-multiplatform-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "jetbrains-compose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
android-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-gradle-plugin" }
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ben-manes-versions = "com.github.ben-manes.versions:0.53.0"
